import sharp from 'sharp';

/**
 * EU AI Act Article 50 transparency obligations applied from 2 August 2026 and
 * the Commission's guidelines state the artistic exemption does not cover
 * commercial marketing or product photography. Synthetic imagery must therefore
 * carry a machine-readable marking, so every asset is stamped on the way out
 * rather than at export time, where it could be skipped.
 */

export type Jurisdiction = 'eu' | 'es' | 'us' | 'uk' | 'fr' | 'no' | 'other';

export interface ProvenanceInput {
  shootId: string;
  providerIds: string[];
  generatedAt: Date;
  /** True when a synthetic human appears, which raises extra duties. */
  depictsSyntheticModel: boolean;
}

/** IPTC DigitalSourceType for content wholly generated by a model. */
const TRAINED_ALGORITHMIC_MEDIA =
  'http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia';

export async function stamp(buffer: Buffer, input: ProvenanceInput): Promise<Buffer> {
  return sharp(buffer)
    .withMetadata({
      exif: {
        IFD0: {
          ImageDescription: 'AI-generated image produced with Amrah Studio',
          Software: 'Amrah Studio',
          Copyright: `Generated ${input.generatedAt.toISOString()}`,
        },
      },
    })
    .withXmp(buildXmp(input))
    .toBuffer();
}

function buildXmp(input: ProvenanceInput): string {
  // Minimal XMP packet carrying the IPTC digital source type. A full C2PA
  // manifest requires signing with a certificate; this is the interoperable
  // marking that survives the common export paths in the meantime.
  return `<?xpacket begin="" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/">
  <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
    <rdf:Description rdf:about=""
      xmlns:Iptc4xmpExt="http://iptc.org/std/Iptc4xmpExt/2008-02-29/"
      xmlns:dc="http://purl.org/dc/elements/1.1/">
      <Iptc4xmpExt:DigitalSourceType>${TRAINED_ALGORITHMIC_MEDIA}</Iptc4xmpExt:DigitalSourceType>
      <dc:creator>Amrah Studio</dc:creator>
      <dc:identifier>${input.shootId}</dc:identifier>
      <dc:date>${input.generatedAt.toISOString()}</dc:date>
      <dc:source>${input.providerIds.join(', ')}</dc:source>
    </rdf:Description>
  </rdf:RDF>
</x:xmpmeta>
<?xpacket end="w"?>`;
}

/**
 * Visible disclosure text. Requirements differ by market, and several regimes
 * carry revenue-percentage fines, so the caption is generated per destination
 * rather than left to the brand to remember.
 */
export function disclosureFor(
  jurisdiction: Jurisdiction,
  input: Pick<ProvenanceInput, 'depictsSyntheticModel'>,
): string | null {
  const model = input.depictsSyntheticModel;

  switch (jurisdiction) {
    case 'eu':
    case 'es':
      return model
        ? 'AI-generated image. The model shown is not a real person.'
        : 'AI-generated image.';
    case 'fr':
      // France requires a retouching notice where a body shape is altered.
      return model
        ? 'Image générée par IA. Photographie retouchée.'
        : 'Image générée par IA.';
    case 'no':
      return model
        ? 'AI-generert bilde. Modellen er ikke en virkelig person.'
        : 'AI-generert bilde.';
    case 'us':
    case 'uk':
      // No blanket labelling mandate, but advertising regulators treat an
      // undisclosed synthetic endorser as misleading.
      return model ? 'AI-generated image. Model is not a real person.' : null;
    default:
      return null;
  }
}
